export const REGISTER = 'AUTH/REGISTER'
export const LOGIN = 'AUTH/LOGIN'
export const LOGOUT = 'AUTH/LOGOUT'

export const SET_REGISTER_LOADING = 'AUTH/SET_REGISTER_LOADING'
export const SET_LOGIN_LOADING = 'AUTH/SET_LOGIN_LOADING'
export const SET_LOGOUT_LOADING = 'AUTH/SET_LOGOUT_LOADING'

export const SET_REGISTER_ERROR = 'AUTH/SET_REGISTER_ERROR'
export const SET_LOGIN_ERROR = 'AUTH/SET_LOGIN_ERROR'
export const SET_LOGOUT_ERROR = 'AUTH/SET_LOGOUT_ERROR'