export const FETCH_CATEGORIES = 'CATEGORIES/FETCH_CATEGORIES'
export const SET_CATEGORIES_FETCHING = 'CATEGORIES/SET_CATEGORIES_FETCHING'
export const SET_CATEGORIES_FETCHING_ERROR = 'CATEGORIES/SET_CATEGORIES_FETCHING_ERROR'