export const FETCH_FAVORITES = 'FAVORITES/FETCH_FAVORITES'
export const ADD_TO_FAVORITES = 'FAVORITES/ADD_TO_FAVORITES'
export const REMOVE_FROM_FAVORITES = 'FAVORITES/REMOVE_FROM_FAVORITES'

export const SET_FAVORITES_LOADING = 'FAVORITES/SET_FAVORITES_LOADING'
export const SET_FAVORITES_LOADING_ERROR = 'FAVORITES/SET_FAVORITES_LOADING_ERROR'