export const FETCH_RECENT = 'RECENT/FETCH_RECENT'
export const ADD_TO_RECENT = 'RECENT/ADD_TO_RECENT'
export const REMOVE_FROM_RECENT = 'RECENT/REMOVE_FROM_RECENT'

export const SET_RECENT_LOADING = 'RECENT/SET_RECENT_LOADING'
export const SET_RECENT_LOADING_ERROR = 'RECENT/SET_RECENT_LOADING_ERROR'